config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'pages#home'

  get '/import', to: 'import#index'
  post '/import', to: 'import#import'
  delete '/clean', to: 'import#delete'
  get '/import/files', to: 'import#files'
  get '/import/file', to: 'import#file'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/unit.rb
# frozen_string_literal: true

# Unit model.
class Unit < ApplicationRecord
  default_scope { order(name: :asc) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base application controller.
class ApplicationController < ActionController::Base
  protect_from_forgery

  add_flash_types :success
end

app/controllers/import_controller.rb
# frozen_string_literal: true

# Imports data.
class ImportController < ApplicationController
  def index
    @sources = %i[json csv].map { |source| source.to_s.upcase }
  end

  def import
    command = EnqueueImportJob.call(import_params)
    return redirect_to root_path, success: 'Import job has been queued.' if
      command.success?

    redirect_to import_path, error: command.errors
  end

  def files
    command = GetDataFiles.call(files_params[:type])
    if command.success?
      render json: command.result
    else
      render json: { errors: command.errors },
             status: :internal_server_error
    end
  end

  def file
    command = GetFileContents.call(file_params[:name], type: file_params[:type])
    if command.success?
      render json: { contents: command.result }
    else
      render json: { errors: command.errors },
             status: :internal_server_error
    end
  end

  def delete
    units = Unit.count
    redirect_to root_path, success: "#{units} deleted." if Unit.delete_all
  end

  def import_params
    params.require(:import).permit(:source, :resource, :base_path)
  end

  def files_params
    params.require(:file).permit(:type)
  end

  def file_params
    params.require(:file).permit(:type, :name)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Controller for static pages.
class PagesController < ApplicationController
  def home
    @units = Unit.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/syntax_helper.rb
# frozen_string_literal: true

# Used for syntax highlighting.
module SyntaxHelper
  def highlight(contents, language: :ruby)
    formatter = Rouge::Formatters::HTML.new(css_class: 'highlight solarized-dark')
    lexer = Rouge::Lexer.find(language)
    formatter.format(lexer.lex(contents))
  end
end

app/views/import/_form.html.erb
<%= form_for :import, url: import_path do |f|%>
  <div class="form-group">
    <%= f.label :source, class: 'control-label' %>
    <%= f.select :source, @sources, {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :resource, class: 'control-label' %>
    <%= f.select :resource, [], {}, { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.label :base_path, class: 'control-label' %>
    <%= f.text_field :base_path, class: 'form-control' %>
  </div>
  <%= f.submit 'Import', class: 'btn btn-primary' %>
<% end %>

app/views/import/_script.html.erb
<script>
 $(function () {
   const $sources = $('#import_source')
   const $files = $('#import_resource')
   const $fileContents = $('#file_contents')

   $sources.on('change', function () {
     const source = $sources.val()

     $.ajax('<%= import_files_path %>', {
       type: 'get',
       data: { file: { type: source } },
       success: function (response) {
         $files.empty()

         response.map(function (file) {
           const $option = $('<option />').attr('value', file)
                                          .text(file)
           $files.append($option)
         })

         $files.change()
       }
     })
   }).change()

   $files.on('change', function () {
     const type = $sources.val()
     const name = $files.val()

     if (name === null) {
       return
     }

     $.ajax('<%= import_file_path %>', {
       type: 'get',
       data: { file: { type: type, name: name }},
       success: function (response) {
         $fileContents.html(response.contents)
       }
     })
   }).change()
 })
</script>

app/views/import/index.html.erb
<div class="row">
  <div class="col">
    <div class="row">
      <div class="col-md-4">
        <h3>Import</h3>
        <%= render 'form' %>
      </div>
      <div class="col-md-8">
        <h3>File preview</h3>
        <div class="contents-container highlight solarized-dark" id="file_contents">
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for(:inline_javascript) do %>
  <%= render 'script' %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="row">
    <div class="col">
      <div class="alert alert-<%= type %> alert-dismissable fade show" role="alert">
        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div id="main-menu" class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Import', import_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Clean units', clean_path, class: 'nav-link', method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EtlStarterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <div class="container">
      <main role="main">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </main>
    </div>
    <%= content_for(:inline_javascript) if content_for?(:inline_javascript) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="col">
    <% if @units.empty? %>
      <div class="text-center">
        <h4>There are no units yet</h4>
        <p>Go to the import page and import some files.</p>
        <%= link_to 'Go to import', import_path, class: 'btn btn-primary btn-lg' %>
      </div>
    <% else %>
      <div class="table-responsive table-fixed-header">
        <table class="table table-bordered table-striped table-hover">
          <thead class="thead-dark">
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Name</th>
              <th scope="col">Price</th>
              <th scope="col">Description</th>
              <th scope="col">Area</th>
              <th scope="col">UOM</th>
            </tr>
          </thead>
          <tbody>
            <%= render @units %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/units/_unit.html.erb
<tr>
  <td scope="row"><%= unit.id %></td>
  <td><%= unit.name %></td>
  <td><%= unit.price %></td>
  <td><%= unit.description %></td>
  <td><%= unit.area %></td>
  <td><%= unit.uom %></td>
</tr>